GraphQL >= 15.1.0 types fix (#86)
* Remove @types/graphql , which is now just a stub as the main graphql package includes its own types

* Bump development version of graphql (and graphql-tools to a version that supports graphql 15+)

* Fix a TypeScript compile error with new graphqls not finding the Maybe type

graphql moved the Maybe utility internally from the default export of `graphql/tsutils/maybe` to a named export of `graphql/jsutils/maybe`. This breaks `graphql-jit`s shipped types when using a new `graphql` version where Maybe has moved:

```
src/execution.ts:36:19 - error TS2307: Cannot find module 'graphql/tsutils/Maybe' or its corresponding type declarations.

36 import Maybe from "graphql/tsutils/Maybe";
                     ~~~~~~~~~~~~~~~~~~~~~~~
```

We could just update the paths to reference the new location, but then `graphql-jit` would strictly require graphql>=15.1.0 to typecheck as old graphqls wouldn't have anything at the new path. This requirement seems kind of silly just to fix a small typescript issue. In order to support both old and new versions of `graphql`'s types, I think it's easiest to just move the type inside this repo since it's really simple. TypeScript will find it equivalent to the one from graphql, and we can import it from the same path regardless of graphql version.