Upgrade TypeScript to 3.9.5 (fixing a tiny bug in the process) (#85)
* Bump typescript to latest

* Fix a typechecking bug that newer TypeScripts catch

Newer typescripts now catch a valid issue where a property was expected to be defined while being undefined. After bumping the compiler, this came up:

```
$ yarn run tsc --noEmit
src/ast.ts:374:52 - error TS2322: Type 'undefined' is not assignable to type 'ObjectPath'.

374     return { value: null, variables: [{ valueNode, path: undefined }] };
                                                       ~~~~

  src/ast.ts:338:3
    338   path: ObjectPath;
          ~~~~
    The expected type comes from property 'path' which is declared here on type 'MissingVariablePath'
```

Since this code has been like this for a while and works just fine, this just updates the types to reflect that the `path` of a `MissingVariablePath` can be undefined, and updates the functions that use it to be a bit simpler when it is undefined.

* Bump @types/node to fix a mismatched node types issue

Before this change, with the newer typescript compiler, this compile issue came up:

```
kamloop ~/C/graphql-jit (da80a9f...) ➜  yarn run tsc --noEmit
yarn run v1.22.4
$ /Users/airhorns/Code/graphql-jit/node_modules/.bin/tsc --noEmit
node_modules/@types/node/index.d.ts:177:11 - error TS2300: Duplicate identifier 'IteratorResult'.

177 interface IteratorResult<T> { }
              ~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
            ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.

node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.

41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
        ~~~~~~~~~~~~~~

  node_modules/@types/node/index.d.ts:177:11
    177 interface IteratorResult<T> { }
                  ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.
```

Bumping @types/node to reflect changes to typescript's internal lib types fixes this issue.