Bump @types/node to fix a mismatched node types issue
Before this change, with the newer typescript compiler, this compile issue came up:

```
kamloop ~/C/graphql-jit (da80a9f...) ➜  yarn run tsc --noEmit
yarn run v1.22.4
$ /Users/airhorns/Code/graphql-jit/node_modules/.bin/tsc --noEmit
node_modules/@types/node/index.d.ts:177:11 - error TS2300: Duplicate identifier 'IteratorResult'.

177 interface IteratorResult<T> { }
              ~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
            ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.

node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.

41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
        ~~~~~~~~~~~~~~

  node_modules/@types/node/index.d.ts:177:11
    177 interface IteratorResult<T> { }
                  ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.
```

Bumping @types/node to reflect changes to typescript's internal lib types fixes this issue.